# Generated by Django 5.1.3 on 2024-11-30 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0006_file_description_file_download_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='files',
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
