# Generated by Django 5.1.3 on 2024-11-30 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0007_remove_message_files_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=11),
            preserve_default=False,
        ),
    ]
