# Generated by Django 5.1.3 on 2024-11-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='unique_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
